
[[constraint]]
  name = "github.com/valyala/fasthttp"
  version = "20160617.0.0"

[[constraint]]
  name = "github.com/buaazp/fasthttprouter"
  version = "0.1.1"

[[constraint]]
  name = "github.com/alexcesaro/statsd"
  version = "2.0.0"

[[constraint]]
  name = "github.com/alecthomas/kingpin"
  version = "2.2.5"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-multierror"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/JaSei/pathutil-go"
  version = "0.1.0"
